### PR TITLE
Update swagger docs for API

### PR DESCRIPTION
**Pull request by haideriqbal**
This is how `Help` tab would look.

Screenshot 2024-06-12 at 15 24 35

### CODE REVIEW

**Comment by henrietteharmse** [comment]
Please update examples you provide to refer to an individual/property/class if you dealing with a individual/property/class api.

Make use of DUO for your examples as the is an ontology that does not change.

**Comment by henrietteharmse** [comment]
Please add description of parameters (both path and request) with examples.

**Comment by henrietteharmse** [comment]
These parameters are added the API docs: `sort=string&forceFirstAndLastRels=true`.
Please remove.

**Comment by jamesamcl** [comment]
I think IRIs have to be double URL encoded not just URL encoded.

**Comment by haideriqbal** [comment]
> I think IRIs have to be double URL encoded not just URL encoded.

yes they do, swagger encodes them once as well so for examples to run in the swagger docs we need to provide it URL encoded iri

**Review by henrietteharmse — APPROVED** [review]

**Pull request merged**
