### PR TITLE
Update exact synonym display on frontend

### PR DESCRIPTION
**Pull request by haideriqbal**
solves this: https://github.com/EBISPOT/ols4/issues/368

### CODE REVIEW

**Review by matentzn — COMMENTED** [review]
Awesome that this is being attacked! Good to see.

Is there a plan to add support for broad, narrow and related synonyms? Especially the latter has a lot of examples across ontologies!

**Comment by haideriqbal** [comment]
> Awesome that this is being attacked! Good to see.
> 
> Is there a plan to add support for broad, narrow and related synonyms? Especially the latter has a lot of examples across ontologies!

@matentzn this change atm differentiate between exactMatch synonym and considers broad/narrow/related synonym as close match synonyms ... have a look at the below screenshot

Screenshot 2024-11-11 at 12 05 19


But if you want we can separate the related synonyms bit as well.. so on UI we can have something like:

exactSynonym -> ......
relatedSynonym -> .............
closestSynonym -> ................

**Comment by matentzn** [comment]
Why not go all on and separate them all as they are curated? Ontologies that make the effort to separate would certainly want to see exactly what they have curated? I am not concerned at all about a longer display, I think this information is very useful, and in fact, we have the opportunity here to have ontology developers separate more cleanly between these synonym types!

**Comment by matentzn** [comment]
(And as per naming, I would just use "Close synonyms", "Related synonym", "Broad synonyms" and "Narrow synonyms", I don't know where the "match" comes from in your display)..

Looks good though!

**Comment by jamesamcl** [comment]
I agree with @matentzn on both counts, and thanks @haideriqbal this is awesome!

**Comment by haideriqbal** [comment]
will make the necessary changes then. Thanks both

**Comment by haideriqbal** [comment]
Now synonyms will appear as they are curated in the ontology file.

Screenshot 2024-11-11 at 13 22 02

**Comment by matentzn** [comment]
Amazing @haideriqbal!!! Love it!

**Comment by sabrinatoro** [comment]
This is fantastic!!! Thank you @haideriqbal !!

**Review by henrietteharmse — APPROVED** [review]
Looks good!

**Pull request merged**
